# Generated by Django 4.1.7 on 2023-03-11 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('cron_expression', models.CharField(max_length=128)),
            ],
        ),
    ]
