# Generated by Django 4.1.7 on 2023-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='target_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
